#+TITLE: Parameters: parameter setting framework for Common Lisp
#+AUTHOR: Alexey Cherkaev (mobius-eng)

* Scientific computing and models
One of the challenges with scientific computing and modelling
(especially applied in engineering fields) is the sheer number of
parameters each model must contain. Setting up the models might be a
real challenge. Furthermore, it can be convenient for the model to
conduct all the computation in SI units (or any other set, but the
point is - a single set of units) for consistency, but inputs in SI
units might be inconvenient (e.g. specifying something really heavy in
kg or temperature in Kelvin).

* Meet parameters

Parameters is a library that helps to set up such models and also
generates the interface (using Qt) for setting up the models.

At the moment it is capable of setting:
- Single parameters :: simple parameters with a single value. For
     example, mass, velocity, temperature, etc. Each parameter is
     accompanied by name, id (for setting it in a model), units of
     measure, transformer (to transform, for example, to different
     units), constructor (if, for example, an integer value is
     required; by default all parameter values are assumed
     double-floats).
- Perturbed parameters :: similar to single parameters, but an extra
     value of perturbation is included: it adds some white noise at
     the time of setting this parameter into the model (not fully
     supported in interface and not tested yet!).
- Parameter containers :: these parameters contain other (simpler)
     parameters. Container can represent the full model or part of
     it. For example, a full model of an ideal gas state may include
     volume, temperature, pressure and molarity.
- Parameter options :: lets the user choose between alternative
     models. For example, it may let the user choose between ideal gas
     model (for low pressures) and a real gas model (e. g. van der
     Waals). It can also be used if a single parameter allows for
     multiple units: the user can choose which units supply.
- Parameter broadcast :: lets the user to define one parameter that
     will be broadcast to a collection (list) of instances. This is
     especially useful for perturbed parameters as the collection will
     consist of values with the white noise added.

Everything is defined using CLOS and thus user extensions are
possible. The code is thoroughly documented if anyone wants to extend
it. Some formalization still needs to be done (e.g. what is the
minimum implementation requirements are for something to be a 'parameter).

* Extra: YAML configurations

To simplify the input it is possible to specify model parameters in
YAML file. The workflow consists of two steps:
- Specify the defualt configuration in LISP code.
- Use YAML configuration to adjust default configuration.

This way the user does not need to specify the full model in
YAML. Other capabilities and limitations:
- YAML does not need to follow exact LISP names: it is possible to
  specify the synonyms for ids to be used in YAML. This reduces
  verobisity.
- YAML must contain ASCII-characters only: the limitation comes from
  the use of CL-YACLYAML library (needs improvement).

* Extra: Interface

Note: this functionality depends on =qtools= and =qt-libs=. Right now
=qt-libs= is going through the update process and does not work as
expected. Thus, this functionality is considered *not implemented* and
will be updated as soon as =qt-libs= is stabilised.

Once the default configuration of the model is set, it is possible to
set up the interface (using Qt) using =SHOW-MODEL= function of
=PARAMETERS-INERFACE= package as simple as:

#+BEGIN_SRC lisp
  (show-model parameter-model)
#+END_SRC

* Tutorial
See directory =documentation= for the tutorial on how to use
=PARAMETERS= on an example problem. Actual source code for the
tutorial is a part of the tests (=t/parameters-tests.lisp=).

* Changelog
The following was changed:
- General cleanup was performed. =PARAMETER-VALUE-TRANSFORMER=
  function was removed as duplicating
  =PARAMETER-BASE-CONSTRUCTOR=. Also, =-BASE-= infix was dropped in
  some functions.
- The full set of Parameters API was defined.
- Function =PARAMETER= was made "keyword-generic".
- Tests were migrated from FiveAM to Prove.
- Tests were improved to cover more functionality.
- YAML tests were added.
- Documentation updated.
- Interface is working again with master branch of =qt-libs= (not in
  Quicklisp yet, you will need to clone it separately). =qt-libs=
  still contains the bug that may cause a crash under some
  circumstances. The recipe to make it work for now: make sure no
  Smoke and Smoke Qt bindings are installed (under Linux). It will
  pull correct versions and load them automatically.
- Parameter broadcast was added.

* Future improvements

The following needs improvements:
- Improve YAML support: UTF-8 encoding and configuration save.
- Improve interface: dialog placement, object view.
- Add web-interface using Lucerne or Caveman2.
- Manual and tutorials: add more.

* Installation

The library is not in Quicklisp yet. To install, clone the project to
your =local-projects= folder of Quicklisp, start lisp and do
#+BEGIN_SRC lisp
  (ql:quickload :parameters)
#+END_SRC

Was tested on: Windows x86-64 (SBCL), Linux x86-64 (SBCL & CCL), Linux
ARM (Raspberry Pi 3, SBCL).


* License
Copyright (C) 2016, Alexey Cherkaev (mobius-eng)

BSD license (see LICENSE file)
